### ISSUE TITLE
Still Logged in with MsalAuthenticationTemplate

### ISSUE THREAD

**Issue by Lucky38i** [Mimetis/msal-react-tester#14]
So for some reason even with the user logged out, the underlying app still renders which then makes my test fail.

My App
```typescript
const App =  () => {
  return (
    <MsalAuthenticationTemplate interactionType={InteractionType.Redirect}>
      <HomeProvider>
        <Home/>
      </HomeProvider>
    </MsalAuthenticationTemplate>
  )
}
```

Index
```typescript
const pca = new PublicClientApplication(configuration)

ReactDOM.render(
  <React.StrictMode>
    <MsalProvider instance={pca}>
      <App/>
    </MsalProvider>
  </React.StrictMode>,
  document.getElementById("root") as HTMLElement
);
```

Test, for context I am using MSW but that should be unrelated as the app component should not render
```typescript
describe("Authentication Tests", () => {
  beforeAll(() => server.listen());
  afterAll(() => server.close());

  beforeEach(() => {
    msalTester = new MsalReactTester("Redirect")
    msalTester.spyMsal()
  })
  afterEach(() => msalTester.resetSpyMsal())


  test("App renders expected components when not authenticated", async () => {
    await msalTester.isNotLogged()
    const {getByTestId} = render(
      <MsalProvider instance={msalTester.client}>
        <App />
      </MsalProvider>
    );

    await msalTester.waitForRedirect()
    expect(getByTestId("home-test")).toBeNaN()
  });
})

When the user is logged in in another test, the tests perform as per normal. Any ideas what I may be missing here?

**Comment by Mimetis** [comment]
Your code seems legit
Can you share a repository (with the simplest possible example) I can use to reproduce ?

**Comment by Lucky38i** [comment]
Hi @Mimetis Hopefully this is simplified enough https://github.com/Lucky38i/msal-react-test-problem to demonstrate the issue

**Comment by Mimetis** [comment]
When you are using a  `<MsalAuthenticationTemplate />` component, `msal-react` will automatically tries to redirect the page (during onload step) to authenticate the current user.
You can't have a "not logged" page as `msal-react` will trigger the redirect phase.

That's why this test is always true, and you are authenticated at the end:

``` ts
await msalTester.isNotLogged()

const {getByTestId} = render(
  <MsalProvider instance={msalTester.client}>
    <App />
  </MsalProvider>
);
await msalTester.waitForLogin()

// YOU ARE LOGGED

```

btw, I had to replace `await msalTester.waitForRedirect()` with `await msalTester.waitForLogin()` (that should be used with `<MsalAuthenticationTemplate />`

> Note: Sample for `<MsalAuthenticationTemplate />` is here : [SearchPage.test.tsx](https://github.com/Mimetis/msal-react-tester/blob/main/create-react-app-sample/src/pages/SearchPage.test.tsx)

As I said, as the redirect is automatic, you can't have a page 'not logged'.
If you want to have an anonymous page, you need to switch to `<AuthenticatedTemplate />` and `<UnauthenticatedTemplate />`

Otherwise, what you can do is generating a failure, meaning you were not able to login successfully.
I mean, redirect happened, but the login was unsuccessful:

Your `<App />` becomes:

``` ts
export const ErrorComponent: React.FC<MsalAuthenticationResult> = ({ error }) => {
  return <div>
    An Error Occurred: {error ? error.errorCode : "unknown error"}
  </div>
}
const App = () => {
  return (
    <MsalAuthenticationTemplate
      interactionType={InteractionType.Redirect}
      errorComponent={ErrorComponent}
    >
      <span data-testid="home-test">Hello</span>
    </MsalAuthenticationTemplate>
  )
}
```

And your test, with a failure becomes

``` ts
test("App renders expected components when not able to log in correctly", async () => {
  await msalTester.isNotLogged()
  msalTester.generateFailure();

  const {getByTestId} = render(
    <MsalProvider instance={msalTester.client}>
      <App />
    </MsalProvider>
  );

  await msalTester.waitForLogin();

  expect(screen.getByText(`An Error Occurred: ${msalTester.error.errorCode}`)).toBeInTheDocument();
});
```

**Comment by Lucky38i** [comment]
Ah this is a rather elegant solution, I really appreciate the code snippets. Thank you, I'll go ahead and close this issue.
